config/routes.rb
MediaLab::Application.routes.draw do
  devise_for :users

  root to: "landing#index"
  get '/main', to: 'main#index', as: :main

  resources :places, :only => [:index, :show]

  namespace :owner do
    resources :places
  end

  namespace :organizer do
    resources :events
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :name, :description, :email, :phone, :website, :avatar

  belongs_to :user
  
  validates :user,
    :presence => true
  validates :name, :description, :email, :phone,
    :presence => true

  has_attached_file :avatar,
    :styles => { :medium => "300x300>", :thumb => "90x60#", :big => '620x315#' },
    :default_url => "/images/:style/missing.png"

end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :address, :description, :email, :name, :phone,
    :seat_amount, :socket, :wifi, :projector, :avatar

  belongs_to :user
  
  validates :user,
    :presence => true
  validates :address, :description, :email, :name, :phone, :seat_amount,
    :presence => true
  validates :socket, :wifi, :projector,
    :inclusion => {:in => [true, false]}
  validates :email,
    :uniqueness => { :case_sensitive => false }
  validates :seat_amount,
    :numericality => true
  validates :projector, :socket, :wifi,
    :inclusion => {:in => [true, false]}


  has_attached_file :avatar, 
    :styles => { :medium => "300x300>", :thumb => "90x60#", :big => '620x315#' },
    :default_url => "/images/:style/missing.png"

end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
   :rememberable, :trackable, :validatable #, :recoverable

  ROLES = %w{ participant organizer owner }

  has_many :places
  has_many :events

  validates :role,
    :inclusion => { :in => ROLES, :allow_nil => false }

  ROLES.each do |role|
    define_method "#{role}?" do
      self.role == role
    end
  end

end

app/controllers/application_controller.rb
require "app_responder"

class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!

  self.responder = AppResponder
  respond_to :html

  private

  def after_sign_in_path_for(resource)
    main_path
  end

  def after_sign_up_path_for(resource)
    main_path
  end

  def after_sign_out_path_for(resource)
    main_path
  end

  # If helps building an element if there is and ID of it (will try to
  # find it based on that ID)
  # If there is no params[:id] it will create a new instance of given class
  # @param [ActiveRecord::Base] ActiveRecord class type
  # @param [Symbol] from which params[attr] it should take attributes to
  #   build a new instance
  # @param [Symbol] what method it should use to find an element
  # @return [ActiveRecord::Base] your activerecord class instance
  # @example
  #   @element = build_resource(Menu, :menu, :find_by_name!)
  def build_resource(klass, attr = :attr, find_method = :find)
    if params[:id]
      klass.send(find_method, params[:id])
    else
      klass.new(params[attr])
    end
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  layout 'landing'

  skip_before_filter :authenticate_user!

  def index
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  skip_before_filter :authenticate_user!

  def index
    @places = Place.order(:created_at.desc).limit(5)
  end

end

app/controllers/organizer/base_controller.rb
class Organizer::BaseController < ApplicationController

  before_filter :only_for_organizers

  private

  def only_for_organizers
    raise ActiveRecord::RecordNotFound unless current_user.organizer?
  end
  
end

app/controllers/organizer/events_controller.rb
class Organizer::EventsController < Organizer::BaseController

  def index
    respond_with @events = current_user.events
  end

  def new
    respond_with event
  end

  def create
    event.save
    respond_with event, location: organizer_events_path
  end

  def edit
    respond_with event
  end

  def update
    event.update_attributes(params[:event])
    respond_with event, location: organizer_events_path
  end

  def destroy
    event.destroy
    respond_with event, location: organizer_events_path
  end

  private

  def event
    @event ||= build_resource current_user.events, :event
  end

end

app/controllers/owner/base_controller.rb
class Owner::BaseController < ApplicationController

  before_filter :only_for_owners

  private

  def only_for_owners
    raise ActiveRecord::RecordNotFound unless current_user.owner?
  end

end

app/controllers/owner/places_controller.rb
class Owner::PlacesController < Owner::BaseController

  def index
    respond_with @places = current_user.places
  end

  def new
    respond_with place
  end

  def create
    place.save
    respond_with place, location: owner_places_path
  end

  def edit
    respond_with place
  end

  def update
    place.update_attributes(params[:place])
    respond_with place, location: owner_places_path
  end

  def destroy
    place.destroy
    respond_with place, location: owner_places_path
  end

  private

  def place
    @place ||= build_resource current_user.places, :place
  end

end

app/helpers/application_helper.rb
# coding: utf-8

module ApplicationHelper

  # Decides whether or not menu element is active (we are in this menu)
  #
  # @param Array[<ControllerClass>] args list of controllers that we should be
  #   in, to make menu element active, and action names (as string or sym) if
  #   only given action from given controllers will determine that element
  #   is active
  def menu_active?(*args)
    actions = []
    controllers = []

    args.each do |arg|
      if arg.is_a?(String) || arg.is_a?(Symbol)
        actions << arg
      else
        controllers << arg
      end
    end

    is_action = actions.empty? || actions.any?{|action| action.to_s == params[:action].to_s }
    is_controller = controllers.any?{|klass| controller.is_a?(klass)}
    # Check if controller is an instance of a given class
    return is_action && is_controller ? 'active' : 'not-active'
  end

  def icon(name, color = nil)
    css_class = ["icon-#{name}"]
    css_class << 'icon-white' if color
    content_tag(:i, '', :class => css_class)
  end

  def link_to_edit(path, translation = nil, css_class = nil)
    options = {
      :class => css_class ||= 'btn'
    }
    content = "#{icon(:edit)} #{translation || I18n.t('attributes.edit')}"
    link_to content.html_safe, path, options
  end

  def link_to_destroy(path, translation = nil, css_class = nil, options = {})
    options.merge!({
      :class => css_class ||= 'btn btn-danger',
      :method => :delete,
      :confirm => I18n.t('attributes.confirm')
    })
    content = "#{icon(:trash)} #{translation || I18n.t('attributes.destroy')}"
    link_to content.html_safe, path, options
  end

  def link_to_back(path, text = I18n.t('attributes.back'), css_class = nil)
    params = {:class => css_class || 'btn'}
    link_to text, path, params
  end

  def named_roles
    names = { 
      :owner       => 'Właściciel miejsca' ,
      :organizer   => 'Organizator wydarzenia',
      :participant => 'Uczestnik'
    }
    User::ROLES.collect {|r| [names[r.to_sym] ,r] }
  end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title INFO SPOT.edu - Najlepsze bezpłatne warsztaty w Krakowie
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}

    = stylesheet_link_tag "layout/base/bootstrap", "layout/base/bootmagz"

    = javascript_include_tag "libs/jquery/jquery", "twitter/bootstrap", 'libs/jquery/jquery-ujs'
    = csrf_meta_tag
  %body
    .container.main
      .row
        .top-menu
          .span6
            %ul.nav.nav-pills.pull-left

          .span6.socmed-box
            %ul.social_media.pull-right
              %li
                %a.twitter{:href => '#', :title => "Twitter"}
              %li
                %a.facebook{:href => '#', :title => "Facebook"}
              %li
                %a.gplus{:href => '#', :title => "Google Plus"}
              %li
                %a.rss{:href => '#', :title => "RSS"}
      .row
        .span12.header
          .span12.logo
            %a{:href => "index.html"}
            %h1.logo-title
              = image_tag('/assets/layout/landing/logo_black.png', :alt => 'Info sspot')

      %br

      .row
        .span12
          .navbar
            .navbar-inner
              .container
                %ul.nav
                  %li{:class => menu_active?(MainController)}
                    %a{:href => main_path} Strona główna
                  %li
                    %a{:href => "category.html"} Warsztaty
                  %li
                    %a{:href => "category.html"} Miejsca
                  %li
                    %a{:href => "category.html"} Zgłoś pomysł
                  %li
                    %a{:href => "category.html"} Aktualności
                  %li
                    %a{:href => "category.html"} Galeria

                %ul.nav.pull-right
                  - unless current_user
                    %li{:class => menu_active?(Devise::SessionsController)}
                      %a{:href => new_user_session_path} Zaloguj się
                    %li{:class => menu_active?(Devise::RegistrationsController)}
                      %a{:href => new_user_registration_path} Zarejestruj się
                  - else
                    - if current_user.owner?
                      %li{:class => menu_active?(Owner::PlacesController)}
                        %a{:href => owner_places_path} Moje miejsca
                    - if current_user.organizer?
                      %li{:class => menu_active?(Organizer::EventsController)}
                        %a{:href => organizer_events_path} Moje warsztaty

                    %li
                      = link_to 'Wyloguj się', destroy_user_session_path, :method => 'delete'

        .span12
          = bootstrap_flash
          = yield

      %footer#footer
        .row
          .span9.about
            %h4 O nas
            %br
            Info spot jest serwisem, która łączy ludzi szukających możliwości
            rozwoju z osobami organizującymi warsztaty&nbsp;i&nbsp;z&nbsp;miejscami, w których
            można je przeprowadzić. Jest on tworzony dla i przez użytkowników.
            Jesteśmy&nbsp;przekonani, że siłą tego portalu jest społeczność, która
            dostarcza informacji o najciekawszych i darmowych warsztatach w Krakowie.
          .span3.latest-tweets
            %h4 Kontakt
            %br
            %a{:href => "mailto:kontakt@infospot.edu.pl"}
              kontakt@infospot.edu.pl

    %script{:src => "js/jquery-1.7.2.min.js"}
    %script{:src => "js/bootstrap.js"}
    :javascript
      $(document).ready(function(){
          $('.carousel').carousel({
              interval: 2000
          })
      });

app/views/layouts/landing.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title INFO SPOT.edu - Najlepsze bezpłatne warsztaty w Krakowie
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}

    = stylesheet_link_tag "layout/bootstrap", "layout/landing/style"

    = javascript_include_tag "libs/jquery/jquery", "libs/jquery/jquery.easing.1.3", |
      "libs/jquery/jquery.validate", "libs/jquery/jquery.watermark.min",            |
      "libs/jquery/waypoints.min", "libs/jquery/jquery.parallax-1.1.3",             |
      "libs/jquery/theme"
    = csrf_meta_tag
  %body

    .lock-header.hidden-phone
      .container
        .row
          .span4.offset2
            %h4
              Polub nas:
          .span4
            %a{:href => '#'}
              = image_tag 'layout/landing/Pinterest.png'
            %a{:href => '#'}
              = image_tag 'layout/landing/Facebook.png'
            %a{:href => '#'}
              = image_tag 'layout/landing/Twitter.png'
            %a{:href => '#'}
              = image_tag 'layout/landing/Share-This.png'

    .page-wrapper
      .agency-wrap
        .container.page-container.home-container
          .row
            .span12
              .top-nav
                %ul.nav.hidden-phone
                  %li
                    %a.slide-to{:href => "#feature-set", :name => "feature-set"}
                      DOWIEDZ SIĘ WIĘCEJ
                      %i.arrow.arrow-down
                  %li
                    %a{:href => new_user_session_path} ZALOGUJ SIĘ
                  %li
                    %a{:href => main_path} STRONA GŁÓWNA

              .header-main
                %h1
                  = image_tag('/assets/layout/landing/logo.png', :alt => 'Info sspot')

                %h4 Najlepsze bezpłatne warsztaty w Krakowie

                = form_for User.new, :url => user_registration_path, :html => {:class => 'theme-form sign-up-form', :id => 'subForm'} do |f|
                  = f.text_field :email, :class => 'email required', :id => 'email', :placeholder => ''
                  = f.select :role, named_roles

                  %input{:type => "submit", :value => "DOŁĄCZ!"}


      %a.down-tab.hidden-phone{:href => main_path}
        ZNAJDŹ WARSZTATY
        %i.arrow.arrow-down
      .full-width-features.feature-1#feature-set
        .container
          .row

            .span12
              %h1 Info spot łaczy tych, którzy chcą działać!
              %h2
                Masz pomysł, ale nie masz miejsca?
                %br.hidden-phone/
                Masz miejsce, ale nie masz pomysłu?
                %br.hidden-phone/
                Masz motywację, ale nie masz informacji?

          .row
            .span12
              %hr
              %br
            .span3
              %img{:alt => "", :src => "/assets/layout/landing/feature01.png", :style => 'width: 120px;'}
              %h3 PRZEGLĄDAJ
              %p
                Chciałbyś dowiedzieć się czegoś ciekawego? Poznać fajnych ludzi? Rozwinąć swoje pasje? Po to jesteśmy!
            .span3
              %img{:alt => "", :src => "/assets/layout/landing/feature02.png", :style => 'width: 120px;'}
              %h3 ORGANIZUJ
              %p
                Chcesz zorganizować warsztaty, ale nie wiesz, gdzie możesz to zrobić? Tutaj znajdziesz bazę najlepszych miejsc w Krakowie.
            .span3
              %img{:alt => "", :src => "/assets/layout/landing/feature03.png", :style => 'width: 120px;'}
              %h3 INFORMUJ
              %p
                Słyszałeś o ciekawych warsztatach? A może pracujesz w domu kultury, jesteś właścicielem klubu? Chciałbyś przyciągnąć do siebie ludzi? Daj znać!
            .span3
              %img{:alt => "", :src => "/assets/layout/landing/feature04.png", :style => 'width: 120px;'}
              %h3 ZGŁOŚ POMYSŁ
              %p
                W jakich warsztatach chciałbyś wziąć udział? Zainspiruj innych!

      .container.call-to-action
        %a.scroll-top{:href => 'mailto:kontakt@infospot.edu.pl'} kontakt@infospot.edu.pl
      .end_page
        %img{:alt => "logo", :src => "/assets/layout/landing/envelope.png"}

      .footer{:name => "contact"}
        .container.contact-form
          .row
            .span12
              %br
              %br
              %h3 Contact Us
              .map
                %iframe{:frameborder => "0", :height => "250", :marginheight => "0", :marginwidth => "0", :scrolling => "no", :src => "https://maps.google.com/maps?ie=UTF8&q=las+tablas,+madrid&fb=1&hq=las+tablas,&hnear=0xd42287d383766c9:0xad469cc0ed50997d,Madrid,+Espa%C3%B1a&cid=0,0,15011046097507982567&t=m&iwloc=A&ll=40.421889,-3.713523&spn=0.006295,0.006295&output=embed", :width => "100%"}
              %br/
            %form.theme-form{:action => "", :method => "post"}
              .span3
                %input#name-field.required{:name => "namefield", :title => "Name", :type => "text"}
              .span3
                %input#email-field.email.required{:name => "emailfield", :title => "Email", :type => "email"}
              .span3
                %input#phone-field{:name => "phonefield", :title => "Phone", :type => "text"}
              .span3
                %input#company-field{:name => "companyfield", :title => "Company", :type => "text"}
              .span12.comments-textarea
                %textarea#comments-field{:name => "commentsfield", :title => ""}
              .span4.offset4
                %input{:name => "say", :type => "hidden", :value => "hello"}
                %input{:type => "submit", :value => "SUBMIT!"}
        .container
          .copyright
            %a.logo{:href => main_path}
              %img{:alt => "logo", :src => "/assets/layout/landing/logo_small.png"}
            %p
              Utworzono w czasie Media-Labu 2013.
              Copyright 2013

app/views/main/index.html.haml
.row
  / Start Main Content
  .span8
    .row
      .span8
        #myCarousel.carousel.slide
          .carousel-inner
            .item.active
              %img{:alt => "", :src => "/assets/layout/base/slider-1.jpg"}
              .carousel-caption
                %h4 First Thumbnail label
                %p
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                  sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  Ut enim ad minim veniam, quis nostrud.
            .item
              %img{:alt => "", :src => "/assets/layout/base/slider-2.jpg"}
              .carousel-caption
                %h4 Second Thumbnail label
                %p
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                  sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  Ut enim ad minim veniam, quis nostrud.
            .item
              %img{:alt => "", :src => "/assets/layout/base/slider-3.jpg"}
              .carousel-caption
                %h4 Third Thumbnail label
                %p
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                  sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  Ut enim ad minim veniam, quis nostrud.
          %a.left.carousel-control{"data-slide" => "prev", :href => "#myCarousel"} ‹
          %a.right.carousel-control{"data-slide" => "next", :href => "#myCarousel"} ›
    %hr/
    .row
      .span8
        .row
          .span4.left-content
            .widget-title
              %h3 Nadchodzące warsztaty
            .span4.featured-news
              %img{:alt => "", :src => "/assets/layout/base/politics.jpg"}
              %a{:href => "single.html"}
              %h4 Up nominated one of the best movies to be created by disney
              %span.date Posted on July 02, 2011 | 0 comments
              %p Maecenas mattis, tortor ut posuere aliquam, quam enim accumsan purus, auctor placerat orci velit vitae massa. Vivamus non iaculis
            .span4.recent-news
              .item-news
                %a{:href => "single.html"}
                  %img{:alt => "", :src => "/assets/layout/base/hillary_clinton.jpg"}
                %a{:href => "single.html"}
                %h4 Toy Story 3 One of the best movies (Video)
                %span.date Posted on July 02, 2011 | 0 comments
              .item-news
                %a{:href => "single.html"}
                  %img{:alt => "", :src => "/assets/layout/base/hillary_clinton.jpg"}
                %a{:href => "single.html"}
                %h4 Toy Story 3 One of the best movies (Video)
                %span.date Posted on July 02, 2011 | 0 comments
              .item-news
                %a{:href => "single.html"}
                  %img{:alt => "", :src => "/assets/layout/base/hillary_clinton.jpg"}
                %a{:href => "single.html"}
                %h4 Toy Story 3 One of the best movies (Video)
                %span.date Posted on July 02, 2011 | 0 comments
          .span4.right-content
            .widget-title
              %h3 Najnowsze miejsca
            .span4.featured-news
              %img{:alt => "", :src => "/assets/layout/base/business.jpg"}
              %a{:href => "single.html"}
              %h4 Up nominated one of the best movies to be created by disney
              %span.date Posted on July 02, 2011 | 0 comments
              %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore ...
            .span4.recent-news
              .item-news
                %a{:href => "single.html"}
                  %img{:alt => "", :src => "/assets/layout/base/80x60-1.jpg"}
                %a{:href => "single.html"}
                %h4 Toy Story 3 One of the best movies (Video)
                %span.date Posted on July 02, 2011 | 0 comments
              .item-news
                %a{:href => "single.html"}
                  %img{:alt => "", :src => "/assets/layout/base/80x60-1.jpg"}
                %a{:href => "single.html"}
                %h4 Toy Story 3 One of the best movies (Video)
                %span.date Posted on July 02, 2011 | 0 comments
              .item-news
                %a{:href => "single.html"}
                  %img{:alt => "", :src => "/assets/layout/base/80x60-1.jpg"}
                %a{:href => "single.html"}
                %h4 Toy Story 3 One of the best movies (Video)
                %span.date Posted on July 02, 2011 | 0 comments
        %br
        .row
          .span8
            .widget-title
              %h3 Zgłoś pomysł
            .row
              .span4.left-content.big-image-content
                %img{:src => "/assets/layout/base/370x255-1.jpg"}
                .inner-news-title.fixed
                  %h2
                    %a{:href => "single.html"} Sport Title
                  %p Lorem ipsum dolor sit amet, consectetur adipiscing elit integer id nibh ac est.
              .span4.recent-news.right-content
                .item-news
                  %a{:href => "single.html"}
                    %img{:alt => "", :src => "/assets/layout/base/rooney.jpg"}
                  %a{:href => "single.html"}
                  %h4 Toy Story 3 One of the best movies (Video)
                  %span.date Posted on July 02, 2011 | 0 comments
                .item-news
                  %a{:href => "single.html"}
                    %img{:alt => "", :src => "/assets/layout/base/rooney.jpg"}
                  %a{:href => "single.html"}
                  %h4 Toy Story 3 One of the best movies (Video)
                  %span.date Posted on July 02, 2011 | 0 comments
                .item-news
                  %a{:href => "single.html"}
                    %img{:alt => "", :src => "/assets/layout/base/rooney.jpg"}
                  %a{:href => "single.html"}
                  %h4 Toy Story 3 One of the best movies (Video)
                  %span.date Posted on July 02, 2011 | 0 comments
        %br
  / End Main Content
  / Start Right Sidebar
  .span4.right-sidebar
    .row
      .span4.box-widget
        %form.form-search.pull-right
          %input.search-query.search-form{:placeholder => "Type your keyword here !", :type => "text"}
          %button.btn{:type => "submit"} Go
    %br
    .row
      .span4.tab-box.box-widget
        .tabbable
          %ul.nav.nav-tabs
            %li.active
              %a{"data-toggle" => "tab", :href => "#1"}
                %i.icon-star>
                \ Ranking
            %li
              %a{"data-toggle" => "tab", :href => "#2"}
                %i.icon-comment>
                \ Kalendarz
            %li
              %a{"data-toggle" => "tab", :href => "#3"}
                %i.icon-tags>
                \ Tagi
          .tab-content
            #1.tab-pane.active
              .popular
                - @places.each do |place|
                  .item-news
                    %a{:href => place_path(place)}
                      %img{:alt => "", :src => place.avatar(:thumb)}
                    %a{:href => place_path(place)}
                    %h4= place.name
                    %span.date= place.created_at

            #2.tab-pane
              .comments
                .item-news
                  %a{:href => "single.html"}
                    %img{:alt => "", :src => "/assets/layout/base/80x60-1.jpg"}
                  %a{:href => "single.html"}
                  %h4
                    %i Admin :Toy Story 3 One of the best movies (Video)
                  %span.date Posted on July 02, 2011 07:15 AM
                .item-news
                  %a{:href => "single.html"}
                    %img{:alt => "", :src => "/assets/layout/base/80x60-1.jpg"}
                  %a{:href => "single.html"}
                  %h4
                    %i Michael :Toy Story 3 One of the best movies (Video)
                  %span.date Posted on July 02, 2011 20:30 PM
                .item-news
                  %a{:href => "single.html"}
                    %img{:alt => "", :src => "/assets/layout/base/80x60-1.jpg"}
                  %a{:href => "single.html"}
                  %h4
                    %i John : Toy Story 3 One of the best movies (Video)
                  %span.date Posted on July 02, 2011 11:45 am
            #3.tab-pane
              %ul.tags
                %li
                  %a.btn{:href => '#'}
                    %i.icon-tag>
                    Sport
                %li
                  %a.btn{:href => '#'}
                    %i.icon-tag>
                    Politics
                %li
                  %a.btn{:href => '#'}
                    %i.icon-tag>
                    Obama
                %li
                  %a.btn{:href => '#'}
                    %i.icon-tag>
                    Soccer
                %li
                  %a.btn{:href => '#'}
                    %i.icon-tag>
                    Social Media
                %li
                  %a.btn{:href => '#'}
                    %i.icon-tag>
                    Economics
                %li
                  %a.btn{:href => '#'}
                    %i.icon-tag>
                    Musics
                %li
                  %a.btn{:href => '#'}
                    %i.icon-tag>
                    Hollywood Artist

    %br
    .row
      .span4
        .span2.sidebar-left
          .widget-title
            %h3 Categories
          %ul.nav
            %li
              %a{:href => "blog.html"} Category Item
            %li
              %a{:href => "blog.html"} Category Item
            %li
              %a{:href => "blog.html"} Category Item
        .span2.sidebar-right
          .widget-title
            %h3 Archives
          %ul.nav
            %li
              %a{:href => "blog.html"}
                January 2012
                %span.post-count (34)
            %li
              %a{:href => "blog.html"}
                February 2012
                %span.post-count (10)
            %li
              %a{:href => "blog.html"}
                March 2012
                %span.post-count (7)
    %br
    .row
      .span4.box-widget
        .widget-title
          %h3 Find us on Facebook
        .span4.fb-like-box
          %iframe{:allowtransparency => "true", :frameborder => "0", :scrolling => "no", :src => "//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2FInfospotEduPl&width=290&height=350&show_faces=true&colorscheme=light&stream=false&show_border=true&header=true", :style => "border:none; overflow:hidden; width:290px; height:590px;"}
    %br
  / End Right Sidebar

app/views/organizer/events/_form.html.haml
= f.input :avatar
= f.input :name
= f.input :description
= f.input :email
= f.input :phone
= f.input :website

app/views/organizer/events/edit.html.haml
= simple_form_for @event, :url => organizer_event_path(@event), :html => { :class => 'form-horizontal' } do |f|
  = render 'form', :f => f
  = f.button :submit, 'Aktualizuj wydarzenie'

app/views/organizer/events/index.html.haml
= link_to "Dodaj nowy event", new_organizer_event_path, :class => 'btn btn-primary'

%br
%br

%table.table.table-striped.table-bordered.table-hover.table-condensed
  %tr
    %th Miniaturka
    %th Nazwa
    %th Opis
    %th Email
    %th Telefon
    %th Strona www
    %th Opcje
  - @events.each do |event|
    %tr
      %td
        = image_tag event.avatar(:thumb)
      %td
        = event.name
      %td
        = event.description
      %td
        = event.email
      %td
        = event.phone
      %td
        = event.website
      %td
        .btn-group
          = link_to_edit edit_organizer_event_path(event)
          = link_to_destroy organizer_event_path(event)

app/views/organizer/events/new.html.haml
= simple_form_for @event, :url => organizer_events_path, :html => { :class => 'form-horizontal' } do |f|
  = render 'form', :f => f
  = f.button :submit, 'Dodaj wydarzenie'

app/views/owner/places/_form.html.haml
= f.input :avatar
= f.input :name
= f.input :address
= f.input :description
= f.input :email
= f.input :phone
= f.input :seat_amount
= f.input :socket
= f.input :wifi
= f.input :projector

app/views/owner/places/edit.html.haml
= simple_form_for @place, :url => owner_place_path(@place), :html => { :class => 'form-horizontal' } do |f|
  = render 'form', :f => f
  = f.button :submit, 'Aktualizuj miejsce'

app/views/owner/places/index.html.haml
= link_to "Dodaj nowe miejsce", new_owner_place_path, :class => 'btn btn-primary'

%br
%br

%table.table.table-striped.table-bordered.table-hover.table-condensed
  %tr
    %th Miniaturka
    %th Nazwa
    %th Adres
    %th Opis
    %th Email
    %th Telefon
    %th Opcje
  - @places.each do |place|
    %tr
      %td
        = image_tag place.avatar(:thumb)
      %td
        = place.name
      %td
        = place.address
      %td
        = place.description
      %td
        = place.email
      %td
        = place.phone
      %td
        .btn-group
          = link_to_edit edit_owner_place_path(place)
          = link_to_destroy owner_place_path(place)

app/views/owner/places/new.html.haml
= simple_form_for @place, :url => owner_places_path, :html => { :class => 'form-horizontal' } do |f|
  = render 'form', :f => f
  = f.button :submit, 'Dodaj miejsce'